### ISSUE TITLE
错别字更正

### ISSUE THREAD

**Issue by YJBeetle** [YaoXuanZhi/YaoXuanZhi.github.io#1]
https://yaoxuanzhi.github.io/After-Effects-SDK-Guide/?file=001-%E7%AC%AC%E4%B8%80%E7%AB%A0%EF%BC%9A%E4%BB%8B%E7%BB%8D/004-%E6%80%8E%E6%A0%B7%E8%AE%A9AE%E5%92%8C%E6%8F%92%E4%BB%B6%E4%BA%A4%E4%BA%92%E8%B5%B7%E6%9D%A5

“自动情况” -> “自动清空” ？

**Comment by YaoXuanZhi** [comment]
已处理
